name: kakeibo-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pyzaim
      - google-genai
      - python-dotenv
      - requests
      - slack-sdk
      - slack-bolt
      - playwright
      - pandas
      - matplotlib
      - seaborn
